### ISSUE TITLE
Getting error in visualize.py

### ISSUE THREAD

**Issue by Tharun98** [e-lab/pytorch-linknet#5]
Hii,

I am getting this error 'TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not int' in line 54 of visualize.py which forwards to line 115 in linknet.py(x = self.conv1(x)). I understood that the input which we're giving is number of classes, but it is assuming that it's the input variable of the model.
Please help me figure this out.
Thanks in advance.

**Comment by monk42** [comment]
HI,
Did you solved this error?
